name       : fuse-overlayfs
version    : 1.5.0
release    : 1
source     :
    - https://github.com/containers/fuse-overlayfs/archive/refs/tags/v1.5.0.tar.gz : 6c81b65b71067b303aaa9871f512c2cabc23e2b793f19c6c854d01a492b5a923
homepage   : https://github.com/containers/fuse-overlayfs
license    : GPL-3.0-or-later
component  : system.utils
summary    : FUSE implementation for overlayfs 
description: |
    An implementation of overlay+shiftfs in FUSE for rootless containers.
builddeps  :
    - pkgconfig(fuse3)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
